# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: smims_api_development



test: &TEST
  adapter: postgresql
  encoding: utf8
  database: smims_api_test



production:
  adapter: postgresql
  encoding: utf8
  database: smims_api_production
